# .github/workflows/tests.yml
name: TRACK_NMRPIPE
on:
#  schedule:
#    - cron: '0-59 * * *'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: 'current-time'
        with:
          format: 'YYYY-MM-DDTHH:mm:ssZ'

      - name: Checkout repo
        uses: actions/checkout@v2

#      - name: checkout master
#        working-directory: ./nmrpipe-tracker
#        run: |
#          git checkout master

      # Runs a set of commands using the runners shell
      - name: date stamp
        run: |
          touch ./DATE-STAMP
          echo ${{ steps.current-time.outputs.formattedTime }} > nmrpipe-tracker/DATE-STAMP

#       - name: Install SSH key
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.NMRPIPE_PRIVATE_KEY }}
#           name: id_ed25519 # optional
#           known_hosts: ${{ secrets.KNOWN_HOST_GITHUB }}
# #          config: ${{ secrets.CONFIG }} # ssh_config; optional
#           if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: commit
        uses: EndBug/add-and-commit@v7

        with:
          message: test
          cwd: ./nmrpipe-tracker
          add: DATE-STAMP
          branch: main
